// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: catcoin/claim/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryClaimRecordRequest struct {
	Claimer              string   `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryClaimRecordRequest) Reset()         { *m = QueryClaimRecordRequest{} }
func (m *QueryClaimRecordRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClaimRecordRequest) ProtoMessage()    {}
func (*QueryClaimRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a13ada8fa96e646, []int{0}
}
func (m *QueryClaimRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClaimRecordRequest.Unmarshal(m, b)
}
func (m *QueryClaimRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClaimRecordRequest.Marshal(b, m, deterministic)
}
func (m *QueryClaimRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimRecordRequest.Merge(m, src)
}
func (m *QueryClaimRecordRequest) XXX_Size() int {
	return xxx_messageInfo_QueryClaimRecordRequest.Size(m)
}
func (m *QueryClaimRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimRecordRequest proto.InternalMessageInfo

type QueryClaimRecordResponse struct {
	Record               *ClaimRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	NextClaimUmm         uint64       `protobuf:"varint,2,opt,name=next_claim_umm,json=nextClaimUmm,proto3" json:"next_claim_umm,omitempty"`
	NextClaimAtUnix      int64        `protobuf:"varint,3,opt,name=next_claim_at_unix,json=nextClaimAtUnix,proto3" json:"next_claim_at_unix,omitempty"`
	Capped               bool         `protobuf:"varint,4,opt,name=capped,proto3" json:"capped,omitempty"`
	ClaimedUmm           uint64       `protobuf:"varint,5,opt,name=claimed_umm,json=claimedUmm,proto3" json:"claimed_umm,omitempty"`
	ClaimCount           uint64       `protobuf:"varint,6,opt,name=claim_count,json=claimCount,proto3" json:"claim_count,omitempty"`
	LastClaimUnix        int64        `protobuf:"varint,7,opt,name=last_claim_unix,json=lastClaimUnix,proto3" json:"last_claim_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryClaimRecordResponse) Reset()         { *m = QueryClaimRecordResponse{} }
func (m *QueryClaimRecordResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClaimRecordResponse) ProtoMessage()    {}
func (*QueryClaimRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a13ada8fa96e646, []int{1}
}
func (m *QueryClaimRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryClaimRecordResponse.Unmarshal(m, b)
}
func (m *QueryClaimRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryClaimRecordResponse.Marshal(b, m, deterministic)
}
func (m *QueryClaimRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClaimRecordResponse.Merge(m, src)
}
func (m *QueryClaimRecordResponse) XXX_Size() int {
	return xxx_messageInfo_QueryClaimRecordResponse.Size(m)
}
func (m *QueryClaimRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClaimRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClaimRecordResponse proto.InternalMessageInfo

type QueryPoolRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPoolRequest) Reset()         { *m = QueryPoolRequest{} }
func (m *QueryPoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPoolRequest) ProtoMessage()    {}
func (*QueryPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a13ada8fa96e646, []int{2}
}
func (m *QueryPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPoolRequest.Unmarshal(m, b)
}
func (m *QueryPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPoolRequest.Marshal(b, m, deterministic)
}
func (m *QueryPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPoolRequest.Merge(m, src)
}
func (m *QueryPoolRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPoolRequest.Size(m)
}
func (m *QueryPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPoolRequest proto.InternalMessageInfo

type QueryPoolResponse struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	AvailableUmm         uint64   `protobuf:"varint,2,opt,name=available_umm,json=availableUmm,proto3" json:"available_umm,omitempty"`
	DailyClaimLimitUmm   uint64   `protobuf:"varint,3,opt,name=daily_claim_limit_umm,json=dailyClaimLimitUmm,proto3" json:"daily_claim_limit_umm,omitempty"`
	DailyDistributedUmm  uint64   `protobuf:"varint,4,opt,name=daily_distributed_umm,json=dailyDistributedUmm,proto3" json:"daily_distributed_umm,omitempty"`
	DailyRemainingUmm    uint64   `protobuf:"varint,5,opt,name=daily_remaining_umm,json=dailyRemainingUmm,proto3" json:"daily_remaining_umm,omitempty"`
	UtcDay               int64    `protobuf:"varint,6,opt,name=utc_day,json=utcDay,proto3" json:"utc_day,omitempty"`
	NextResetAtUnix      int64    `protobuf:"varint,7,opt,name=next_reset_at_unix,json=nextResetAtUnix,proto3" json:"next_reset_at_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPoolResponse) Reset()         { *m = QueryPoolResponse{} }
func (m *QueryPoolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPoolResponse) ProtoMessage()    {}
func (*QueryPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a13ada8fa96e646, []int{3}
}
func (m *QueryPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPoolResponse.Unmarshal(m, b)
}
func (m *QueryPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPoolResponse.Marshal(b, m, deterministic)
}
func (m *QueryPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPoolResponse.Merge(m, src)
}
func (m *QueryPoolResponse) XXX_Size() int {
	return xxx_messageInfo_QueryPoolResponse.Size(m)
}
func (m *QueryPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPoolResponse proto.InternalMessageInfo

type QueryAuthorityRequest struct {
	IssuerKeyId          string   `protobuf:"bytes,1,opt,name=issuer_key_id,json=issuerKeyId,proto3" json:"issuer_key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAuthorityRequest) Reset()         { *m = QueryAuthorityRequest{} }
func (m *QueryAuthorityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuthorityRequest) ProtoMessage()    {}
func (*QueryAuthorityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a13ada8fa96e646, []int{4}
}
func (m *QueryAuthorityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAuthorityRequest.Unmarshal(m, b)
}
func (m *QueryAuthorityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAuthorityRequest.Marshal(b, m, deterministic)
}
func (m *QueryAuthorityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuthorityRequest.Merge(m, src)
}
func (m *QueryAuthorityRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAuthorityRequest.Size(m)
}
func (m *QueryAuthorityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuthorityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuthorityRequest proto.InternalMessageInfo

type QueryAuthorityResponse struct {
	Authority            *ClaimAuthority `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryAuthorityResponse) Reset()         { *m = QueryAuthorityResponse{} }
func (m *QueryAuthorityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuthorityResponse) ProtoMessage()    {}
func (*QueryAuthorityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a13ada8fa96e646, []int{5}
}
func (m *QueryAuthorityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAuthorityResponse.Unmarshal(m, b)
}
func (m *QueryAuthorityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAuthorityResponse.Marshal(b, m, deterministic)
}
func (m *QueryAuthorityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuthorityResponse.Merge(m, src)
}
func (m *QueryAuthorityResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAuthorityResponse.Size(m)
}
func (m *QueryAuthorityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuthorityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuthorityResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryClaimRecordRequest)(nil), "catcoin.claim.v1.QueryClaimRecordRequest")
	proto.RegisterType((*QueryClaimRecordResponse)(nil), "catcoin.claim.v1.QueryClaimRecordResponse")
	proto.RegisterType((*QueryPoolRequest)(nil), "catcoin.claim.v1.QueryPoolRequest")
	proto.RegisterType((*QueryPoolResponse)(nil), "catcoin.claim.v1.QueryPoolResponse")
	proto.RegisterType((*QueryAuthorityRequest)(nil), "catcoin.claim.v1.QueryAuthorityRequest")
	proto.RegisterType((*QueryAuthorityResponse)(nil), "catcoin.claim.v1.QueryAuthorityResponse")
}

func init() { proto.RegisterFile("catcoin/claim/v1/query.proto", fileDescriptor_8a13ada8fa96e646) }

var fileDescriptor_8a13ada8fa96e646 = []byte{
	// 688 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x76, 0x93, 0x34, 0xb1, 0x13, 0x6b, 0xdb, 0xb1, 0x3f, 0x4b, 0xa8, 0x35, 0x6c, 0x8b, 0xc6,
	0x4a, 0x76, 0x69, 0x4b, 0xaf, 0x04, 0xa1, 0xb6, 0x20, 0xa2, 0x82, 0x2e, 0x14, 0xc4, 0x9b, 0x65,
	0xb2, 0x3b, 0xa4, 0x83, 0xbb, 0x33, 0xdb, 0xdd, 0xd9, 0x92, 0xa5, 0xf4, 0xc6, 0x27, 0x10, 0xc4,
	0x27, 0x10, 0xbc, 0xf1, 0x45, 0xbc, 0xf7, 0x09, 0x04, 0x1f, 0x44, 0xe6, 0xec, 0x6c, 0xb2, 0x26,
	0x44, 0xbd, 0x09, 0x33, 0xe7, 0x7c, 0xdf, 0x39, 0x5f, 0xbe, 0x73, 0x76, 0xd0, 0x96, 0x4f, 0xa4,
	0x2f, 0x18, 0x77, 0xfc, 0x90, 0xb0, 0xc8, 0xb9, 0xdc, 0x77, 0x2e, 0x32, 0x9a, 0xe4, 0x76, 0x9c,
	0x08, 0x29, 0xf0, 0x8a, 0xce, 0xda, 0x90, 0xb5, 0x2f, 0xf7, 0x3b, 0xb3, 0x78, 0x99, 0xc7, 0x34,
	0x2d, 0xf0, 0x9d, 0xb5, 0xa1, 0x18, 0x0a, 0x38, 0x3a, 0xea, 0xa4, 0xa3, 0x5b, 0x43, 0x21, 0x86,
	0x21, 0x75, 0x48, 0xcc, 0x1c, 0xc2, 0xb9, 0x90, 0x44, 0x32, 0xc1, 0x35, 0xc7, 0x3a, 0x44, 0x9b,
	0x6f, 0x54, 0xcb, 0x13, 0x55, 0xd0, 0xa5, 0xbe, 0x48, 0x02, 0x97, 0x5e, 0x64, 0x34, 0x95, 0xd8,
	0x44, 0x2d, 0x68, 0x43, 0x13, 0xd3, 0xe8, 0x1a, 0xbd, 0x45, 0xb7, 0xbc, 0x5a, 0x5f, 0x6b, 0xc8,
	0x9c, 0x65, 0xa5, 0xb1, 0xe0, 0x29, 0xc5, 0x47, 0xa8, 0x99, 0x40, 0x04, 0x58, 0xed, 0x83, 0xbb,
	0xf6, 0xf4, 0xdf, 0xb0, 0xab, 0x34, 0x0d, 0xc6, 0xbb, 0xe8, 0x36, 0xa7, 0x23, 0xe9, 0x01, 0xc8,
	0xcb, 0xa2, 0xc8, 0xac, 0x75, 0x8d, 0x5e, 0xc3, 0xbd, 0xa5, 0xa2, 0x40, 0x38, 0x8b, 0x22, 0xfc,
	0x08, 0xe1, 0x0a, 0x8a, 0x48, 0x2f, 0xe3, 0x6c, 0x64, 0xd6, 0xbb, 0x46, 0xaf, 0xee, 0x2e, 0x8f,
	0x91, 0xc7, 0xf2, 0x8c, 0xb3, 0x11, 0xde, 0x40, 0x4d, 0x9f, 0xc4, 0x31, 0x0d, 0xcc, 0x46, 0xd7,
	0xe8, 0xdd, 0x74, 0xf5, 0x0d, 0xdf, 0x43, 0xed, 0xe2, 0x9f, 0x04, 0xd0, 0x67, 0x01, 0xfa, 0x20,
	0x1d, 0x52, 0x5d, 0x4a, 0x80, 0xe7, 0x8b, 0x8c, 0x4b, 0xb3, 0x59, 0x01, 0x9c, 0xa8, 0x08, 0xbe,
	0x8f, 0x96, 0x43, 0x92, 0x8e, 0xc5, 0x2a, 0x0d, 0x2d, 0xd0, 0xb0, 0xa4, 0xc2, 0x85, 0x5a, 0xce,
	0x46, 0x16, 0x46, 0x2b, 0xe0, 0xd3, 0x6b, 0x21, 0x42, 0x6d, 0xab, 0xf5, 0xad, 0x86, 0x56, 0x2b,
	0x41, 0xed, 0xda, 0x1a, 0x5a, 0x08, 0x28, 0x17, 0x91, 0xb6, 0xba, 0xb8, 0xe0, 0x1d, 0xb4, 0x44,
	0x2e, 0x09, 0x0b, 0xc9, 0x20, 0xa4, 0x55, 0x4f, 0xc6, 0x41, 0xa5, 0x76, 0x1f, 0xad, 0x07, 0x84,
	0x85, 0xb9, 0x56, 0x13, 0xb2, 0x88, 0x49, 0x00, 0xd7, 0x01, 0x8c, 0x21, 0x09, 0x9a, 0x5e, 0xaa,
	0x94, 0xa2, 0x1c, 0x94, 0x94, 0x80, 0xa5, 0x32, 0x61, 0x83, 0x4c, 0x6a, 0x2f, 0x1a, 0x40, 0xb9,
	0x03, 0xc9, 0xd3, 0x49, 0x4e, 0x71, 0x6c, 0x54, 0x84, 0xbd, 0x84, 0x46, 0x84, 0x71, 0xc6, 0x87,
	0x15, 0xf7, 0x56, 0x21, 0xe5, 0x96, 0x19, 0x85, 0xdf, 0x44, 0xad, 0x4c, 0xfa, 0x5e, 0x40, 0x72,
	0x30, 0xb0, 0xee, 0x36, 0x33, 0xe9, 0x9f, 0x92, 0x7c, 0x3c, 0xc3, 0x84, 0xa6, 0x54, 0x8e, 0x67,
	0xd8, 0x9a, 0xcc, 0xd0, 0x55, 0x89, 0x62, 0x86, 0xd6, 0x63, 0xb4, 0x0e, 0x66, 0x1d, 0x67, 0xf2,
	0x5c, 0x24, 0x4c, 0xe6, 0xe5, 0x76, 0x5a, 0x68, 0x89, 0xa5, 0x69, 0x46, 0x13, 0xef, 0x3d, 0xcd,
	0x3d, 0x16, 0x68, 0xe3, 0xda, 0x45, 0xf0, 0x05, 0xcd, 0x9f, 0x07, 0xd6, 0x5b, 0xb4, 0x31, 0x4d,
	0xd6, 0x76, 0x3f, 0x41, 0x8b, 0xa4, 0x0c, 0xea, 0x3d, 0xed, 0xce, 0xd9, 0xd3, 0x09, 0x79, 0x42,
	0x39, 0xf8, 0x52, 0x47, 0x0b, 0x50, 0x1a, 0x7f, 0x34, 0x50, 0xbb, 0xb2, 0xcf, 0xf8, 0xe1, 0x6c,
	0x99, 0x39, 0x1f, 0x58, 0x67, 0xef, 0x7f, 0xa0, 0x85, 0x60, 0x6b, 0xef, 0xc3, 0x8f, 0x5f, 0x9f,
	0x6a, 0xbb, 0xd8, 0x72, 0x66, 0x9e, 0x00, 0x38, 0xa4, 0xce, 0x95, 0xfe, 0x3a, 0xaf, 0xb1, 0x40,
	0x0d, 0xb5, 0x5b, 0xd8, 0x9a, 0x53, 0xbf, 0xb2, 0x8d, 0x9d, 0x9d, 0xbf, 0x62, 0x74, 0xf3, 0x6d,
	0x68, 0x6e, 0xe2, 0x8d, 0xd9, 0xe6, 0xb1, 0x6a, 0xf4, 0xd9, 0x40, 0x8b, 0x63, 0x9b, 0xf0, 0x83,
	0x39, 0x25, 0xa7, 0x47, 0xd8, 0xe9, 0xfd, 0x1b, 0xa8, 0x05, 0x1c, 0x81, 0x00, 0x07, 0xf7, 0x67,
	0x05, 0x94, 0x33, 0x61, 0x34, 0x75, 0xae, 0xfe, 0xd8, 0x88, 0xeb, 0xa7, 0xaf, 0xbe, 0xff, 0xdc,
	0xbe, 0xf1, 0xee, 0xd9, 0x90, 0xc9, 0xf3, 0x6c, 0x60, 0xfb, 0x22, 0x72, 0x52, 0xc2, 0x7d, 0x11,
	0x47, 0x22, 0x1b, 0x48, 0xea, 0x44, 0x79, 0x3f, 0x12, 0x03, 0x16, 0xd2, 0xbe, 0x7f, 0x4e, 0x54,
	0xcd, 0xe2, 0xb7, 0xe8, 0xd0, 0x27, 0x71, 0xec, 0x8c, 0x74, 0x1f, 0x78, 0x65, 0x07, 0x4d, 0x78,
	0x32, 0x0f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x42, 0x8d, 0x3a, 0xc5, 0xb6, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	ClaimRecord(ctx context.Context, in *QueryClaimRecordRequest, opts ...grpc.CallOption) (*QueryClaimRecordResponse, error)
	Pool(ctx context.Context, in *QueryPoolRequest, opts ...grpc.CallOption) (*QueryPoolResponse, error)
	Authority(ctx context.Context, in *QueryAuthorityRequest, opts ...grpc.CallOption) (*QueryAuthorityResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ClaimRecord(ctx context.Context, in *QueryClaimRecordRequest, opts ...grpc.CallOption) (*QueryClaimRecordResponse, error) {
	out := new(QueryClaimRecordResponse)
	err := c.cc.Invoke(ctx, "/catcoin.claim.v1.Query/ClaimRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Pool(ctx context.Context, in *QueryPoolRequest, opts ...grpc.CallOption) (*QueryPoolResponse, error) {
	out := new(QueryPoolResponse)
	err := c.cc.Invoke(ctx, "/catcoin.claim.v1.Query/Pool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Authority(ctx context.Context, in *QueryAuthorityRequest, opts ...grpc.CallOption) (*QueryAuthorityResponse, error) {
	out := new(QueryAuthorityResponse)
	err := c.cc.Invoke(ctx, "/catcoin.claim.v1.Query/Authority", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	ClaimRecord(context.Context, *QueryClaimRecordRequest) (*QueryClaimRecordResponse, error)
	Pool(context.Context, *QueryPoolRequest) (*QueryPoolResponse, error)
	Authority(context.Context, *QueryAuthorityRequest) (*QueryAuthorityResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ClaimRecord(ctx context.Context, req *QueryClaimRecordRequest) (*QueryClaimRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimRecord not implemented")
}
func (*UnimplementedQueryServer) Pool(ctx context.Context, req *QueryPoolRequest) (*QueryPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pool not implemented")
}
func (*UnimplementedQueryServer) Authority(ctx context.Context, req *QueryAuthorityRequest) (*QueryAuthorityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authority not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ClaimRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClaimRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClaimRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcoin.claim.v1.Query/ClaimRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClaimRecord(ctx, req.(*QueryClaimRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Pool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Pool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcoin.claim.v1.Query/Pool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Pool(ctx, req.(*QueryPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Authority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuthorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Authority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcoin.claim.v1.Query/Authority",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Authority(ctx, req.(*QueryAuthorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catcoin.claim.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimRecord",
			Handler:    _Query_ClaimRecord_Handler,
		},
		{
			MethodName: "Pool",
			Handler:    _Query_Pool_Handler,
		},
		{
			MethodName: "Authority",
			Handler:    _Query_Authority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catcoin/claim/v1/query.proto",
}
