// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: catcoin/claim/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Voucher 是链下资格服务签发、链上验证的一次性凭证。
type Voucher struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CredentialId         string   `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	ExpiresAtUnix        int64    `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	IssuerKeyId          string   `protobuf:"bytes,5,opt,name=issuer_key_id,json=issuerKeyId,proto3" json:"issuer_key_id,omitempty"`
	Signature            []byte   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voucher) Reset()         { *m = Voucher{} }
func (m *Voucher) String() string { return proto.CompactTextString(m) }
func (*Voucher) ProtoMessage()    {}
func (*Voucher) Descriptor() ([]byte, []int) {
	return fileDescriptor_36faa925030f1643, []int{0}
}
func (m *Voucher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voucher.Unmarshal(m, b)
}
func (m *Voucher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voucher.Marshal(b, m, deterministic)
}
func (m *Voucher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voucher.Merge(m, src)
}
func (m *Voucher) XXX_Size() int {
	return xxx_messageInfo_Voucher.Size(m)
}
func (m *Voucher) XXX_DiscardUnknown() {
	xxx_messageInfo_Voucher.DiscardUnknown(m)
}

var xxx_messageInfo_Voucher proto.InternalMessageInfo

// MsgClaim 由领取地址本人签名；金额完全由链上状态机计算。
type MsgClaim struct {
	Claimer              string   `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
	Voucher              Voucher  `protobuf:"bytes,2,opt,name=voucher,proto3" json:"voucher"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClaim) Reset()         { *m = MsgClaim{} }
func (m *MsgClaim) String() string { return proto.CompactTextString(m) }
func (*MsgClaim) ProtoMessage()    {}
func (*MsgClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_36faa925030f1643, []int{1}
}
func (m *MsgClaim) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClaim.Unmarshal(m, b)
}
func (m *MsgClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClaim.Marshal(b, m, deterministic)
}
func (m *MsgClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaim.Merge(m, src)
}
func (m *MsgClaim) XXX_Size() int {
	return xxx_messageInfo_MsgClaim.Size(m)
}
func (m *MsgClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaim.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaim proto.InternalMessageInfo

type MsgClaimResponse struct {
	ClaimedUmm           uint64   `protobuf:"varint,1,opt,name=claimed_umm,json=claimedUmm,proto3" json:"claimed_umm,omitempty"`
	TotalClaimedUmm      uint64   `protobuf:"varint,2,opt,name=total_claimed_umm,json=totalClaimedUmm,proto3" json:"total_claimed_umm,omitempty"`
	NextClaimUmm         uint64   `protobuf:"varint,3,opt,name=next_claim_umm,json=nextClaimUmm,proto3" json:"next_claim_umm,omitempty"`
	NextClaimAtUnix      int64    `protobuf:"varint,4,opt,name=next_claim_at_unix,json=nextClaimAtUnix,proto3" json:"next_claim_at_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgClaimResponse) Reset()         { *m = MsgClaimResponse{} }
func (m *MsgClaimResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimResponse) ProtoMessage()    {}
func (*MsgClaimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36faa925030f1643, []int{2}
}
func (m *MsgClaimResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgClaimResponse.Unmarshal(m, b)
}
func (m *MsgClaimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgClaimResponse.Marshal(b, m, deterministic)
}
func (m *MsgClaimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimResponse.Merge(m, src)
}
func (m *MsgClaimResponse) XXX_Size() int {
	return xxx_messageInfo_MsgClaimResponse.Size(m)
}
func (m *MsgClaimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Voucher)(nil), "catcoin.claim.v1.Voucher")
	proto.RegisterType((*MsgClaim)(nil), "catcoin.claim.v1.MsgClaim")
	proto.RegisterType((*MsgClaimResponse)(nil), "catcoin.claim.v1.MsgClaimResponse")
}

func init() { proto.RegisterFile("catcoin/claim/v1/tx.proto", fileDescriptor_36faa925030f1643) }

var fileDescriptor_36faa925030f1643 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x6a, 0xdb, 0x30,
	0x1c, 0xc6, 0xeb, 0x26, 0x69, 0xda, 0x7f, 0x92, 0xa5, 0x13, 0x83, 0x39, 0x66, 0xac, 0xc1, 0x1b,
	0x23, 0x64, 0xc4, 0xa6, 0xdd, 0x69, 0xbb, 0xad, 0x3d, 0x94, 0x30, 0x72, 0x31, 0x64, 0x87, 0x5d,
	0x8c, 0x22, 0x0b, 0x47, 0x2c, 0x92, 0x8c, 0x25, 0x07, 0xe7, 0x36, 0xf6, 0x44, 0x65, 0x4f, 0xd1,
	0xcb, 0x5e, 0x61, 0xb0, 0x53, 0x5f, 0x63, 0x58, 0xb2, 0x9b, 0x6e, 0xa3, 0x97, 0x20, 0x7d, 0xdf,
	0x2f, 0x7f, 0xf9, 0xfb, 0xf8, 0xc3, 0x88, 0x60, 0x4d, 0x24, 0x13, 0x21, 0xd9, 0x60, 0xc6, 0xc3,
	0xed, 0x79, 0xa8, 0xcb, 0x20, 0xcb, 0xa5, 0x96, 0xe8, 0xb4, 0xb6, 0x02, 0x63, 0x05, 0xdb, 0x73,
	0xef, 0x39, 0x91, 0x8a, 0x4b, 0x15, 0x72, 0x95, 0x56, 0x24, 0x57, 0xa9, 0x45, 0xbd, 0x67, 0xa9,
	0x4c, 0xa5, 0x39, 0x86, 0xd5, 0xc9, 0xaa, 0xfe, 0x4f, 0x07, 0xba, 0x9f, 0x65, 0x41, 0xd6, 0x34,
	0x47, 0x23, 0x38, 0x26, 0x6b, 0xcc, 0x44, 0xcc, 0x12, 0xd7, 0x19, 0x3b, 0x93, 0x93, 0xa8, 0x6b,
	0xee, 0xf3, 0x04, 0xb9, 0xd0, 0xc5, 0x49, 0x92, 0x53, 0xa5, 0xdc, 0x43, 0xeb, 0xd4, 0x57, 0xf4,
	0x0a, 0x06, 0x24, 0xa7, 0x09, 0x15, 0x9a, 0xe1, 0x4d, 0xf5, 0xcf, 0x96, 0xf1, 0xfb, 0x7b, 0x71,
	0x9e, 0xa0, 0x37, 0x30, 0xa4, 0x65, 0xc6, 0x72, 0xaa, 0x62, 0xac, 0xe3, 0x42, 0xb0, 0xd2, 0x6d,
	0x8f, 0x9d, 0x49, 0x2b, 0x1a, 0xd4, 0xf2, 0x47, 0xbd, 0x14, 0xac, 0x44, 0x3e, 0x0c, 0x98, 0x52,
	0x05, 0xcd, 0xe3, 0xaf, 0x74, 0x57, 0x0d, 0xeb, 0x98, 0x61, 0x3d, 0x2b, 0x7e, 0xa2, 0xbb, 0x79,
	0x82, 0x5e, 0xc0, 0x89, 0x62, 0xa9, 0xc0, 0xba, 0xc8, 0xa9, 0x7b, 0x34, 0x76, 0x26, 0xfd, 0x68,
	0x2f, 0xf8, 0x1c, 0x8e, 0x17, 0x2a, 0xbd, 0xaa, 0xda, 0xa8, 0x3e, 0xda, 0xd4, 0x42, 0xf3, 0xfb,
	0x38, 0xf6, 0x8a, 0xde, 0x43, 0x77, 0x6b, 0x43, 0x9b, 0x38, 0xbd, 0x8b, 0x51, 0xf0, 0x6f, 0x91,
	0x41, 0xdd, 0xca, 0x65, 0xfb, 0xf6, 0xd7, 0xd9, 0x41, 0xd4, 0xf0, 0x1f, 0xfa, 0xdf, 0xef, 0x6e,
	0xa6, 0xcd, 0x20, 0xff, 0x87, 0x03, 0xa7, 0xcd, 0x7b, 0x11, 0x55, 0x99, 0x14, 0x8a, 0xa2, 0x33,
	0xe8, 0x59, 0x3f, 0x89, 0x0b, 0xce, 0xcd, 0xdb, 0xed, 0x08, 0x6a, 0x69, 0xc9, 0x39, 0x9a, 0xc2,
	0x53, 0x2d, 0x35, 0xde, 0xc4, 0x0f, 0xb1, 0x43, 0x83, 0x0d, 0x8d, 0x71, 0xb5, 0x67, 0x5f, 0xc3,
	0x13, 0x41, 0x4b, 0x6d, 0x51, 0x03, 0xb6, 0x0c, 0xd8, 0xaf, 0x54, 0xc3, 0x55, 0xd4, 0x5b, 0x40,
	0x0f, 0xa8, 0xbf, 0x3b, 0x1e, 0xde, 0x93, 0xb6, 0xe5, 0x8b, 0x25, 0xb4, 0x16, 0x2a, 0x45, 0xd7,
	0xd0, 0xb1, 0x3d, 0x79, 0xff, 0x87, 0x6f, 0x32, 0x79, 0xfe, 0xe3, 0x5e, 0x93, 0xd7, 0xeb, 0x7c,
	0xbb, 0xbb, 0x99, 0x3a, 0x97, 0x8b, 0xdb, 0xdf, 0x2f, 0x0f, 0xbe, 0x5c, 0xa7, 0x4c, 0xaf, 0x8b,
	0x55, 0x40, 0x24, 0x0f, 0x15, 0x16, 0x44, 0x66, 0x5c, 0x16, 0x2b, 0x4d, 0x43, 0xbe, 0x9b, 0x71,
	0xb9, 0x62, 0x1b, 0x3a, 0x33, 0x4b, 0x15, 0xd6, 0xbf, 0x76, 0xfa, 0x0c, 0x67, 0x59, 0x58, 0xd6,
	0x0b, 0xae, 0x77, 0x19, 0x55, 0xab, 0x23, 0xb3, 0xa0, 0xef, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xb0, 0x50, 0xed, 0x09, 0xfe, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Claim(ctx context.Context, in *MsgClaim, opts ...grpc.CallOption) (*MsgClaimResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Claim(ctx context.Context, in *MsgClaim, opts ...grpc.CallOption) (*MsgClaimResponse, error) {
	out := new(MsgClaimResponse)
	err := c.cc.Invoke(ctx, "/catcoin.claim.v1.Msg/Claim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Claim(context.Context, *MsgClaim) (*MsgClaimResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Claim(ctx context.Context, req *MsgClaim) (*MsgClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Claim not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaim)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catcoin.claim.v1.Msg/Claim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Claim(ctx, req.(*MsgClaim))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catcoin.claim.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Claim",
			Handler:    _Msg_Claim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catcoin/claim/v1/tx.proto",
}
