// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: catcoin/claim/v1/types.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClaimRecord 保存单个地址的确定性领取进度。
type ClaimRecord struct {
	Claimer              string   `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
	ClaimedUmm           uint64   `protobuf:"varint,2,opt,name=claimed_umm,json=claimedUmm,proto3" json:"claimed_umm,omitempty"`
	ClaimCount           uint64   `protobuf:"varint,3,opt,name=claim_count,json=claimCount,proto3" json:"claim_count,omitempty"`
	LastClaimUnix        int64    `protobuf:"varint,4,opt,name=last_claim_unix,json=lastClaimUnix,proto3" json:"last_claim_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimRecord) Reset()         { *m = ClaimRecord{} }
func (m *ClaimRecord) String() string { return proto.CompactTextString(m) }
func (*ClaimRecord) ProtoMessage()    {}
func (*ClaimRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6e88def4c510ddb, []int{0}
}
func (m *ClaimRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimRecord.Unmarshal(m, b)
}
func (m *ClaimRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimRecord.Marshal(b, m, deterministic)
}
func (m *ClaimRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimRecord.Merge(m, src)
}
func (m *ClaimRecord) XXX_Size() int {
	return xxx_messageInfo_ClaimRecord.Size(m)
}
func (m *ClaimRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimRecord proto.InternalMessageInfo

// UsedCredential 防止资格凭证被跨地址或跨交易重放。
type UsedCredential struct {
	CredentialId         string   `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	Claimer              string   `protobuf:"bytes,2,opt,name=claimer,proto3" json:"claimer,omitempty"`
	UsedAtUnix           int64    `protobuf:"varint,3,opt,name=used_at_unix,json=usedAtUnix,proto3" json:"used_at_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsedCredential) Reset()         { *m = UsedCredential{} }
func (m *UsedCredential) String() string { return proto.CompactTextString(m) }
func (*UsedCredential) ProtoMessage()    {}
func (*UsedCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6e88def4c510ddb, []int{1}
}
func (m *UsedCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsedCredential.Unmarshal(m, b)
}
func (m *UsedCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsedCredential.Marshal(b, m, deterministic)
}
func (m *UsedCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsedCredential.Merge(m, src)
}
func (m *UsedCredential) XXX_Size() int {
	return xxx_messageInfo_UsedCredential.Size(m)
}
func (m *UsedCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_UsedCredential.DiscardUnknown(m)
}

var xxx_messageInfo_UsedCredential proto.InternalMessageInfo

// ClaimAuthority 仅保存 Ed25519 公钥，不保存私钥、助记词或种子。
type ClaimAuthority struct {
	IssuerKeyId          string   `protobuf:"bytes,1,opt,name=issuer_key_id,json=issuerKeyId,proto3" json:"issuer_key_id,omitempty"`
	Ed25519PublicKey     []byte   `protobuf:"bytes,2,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"`
	Revoked              bool     `protobuf:"varint,3,opt,name=revoked,proto3" json:"revoked,omitempty"`
	ActivationHeight     int64    `protobuf:"varint,4,opt,name=activation_height,json=activationHeight,proto3" json:"activation_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimAuthority) Reset()         { *m = ClaimAuthority{} }
func (m *ClaimAuthority) String() string { return proto.CompactTextString(m) }
func (*ClaimAuthority) ProtoMessage()    {}
func (*ClaimAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6e88def4c510ddb, []int{2}
}
func (m *ClaimAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimAuthority.Unmarshal(m, b)
}
func (m *ClaimAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimAuthority.Marshal(b, m, deterministic)
}
func (m *ClaimAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimAuthority.Merge(m, src)
}
func (m *ClaimAuthority) XXX_Size() int {
	return xxx_messageInfo_ClaimAuthority.Size(m)
}
func (m *ClaimAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimAuthority proto.InternalMessageInfo

// DailyDistribution 保存当前 UTC 日从固定领取池已转出的数量。
type DailyDistribution struct {
	UtcDay               int64    `protobuf:"varint,1,opt,name=utc_day,json=utcDay,proto3" json:"utc_day,omitempty"`
	DistributedUmm       uint64   `protobuf:"varint,2,opt,name=distributed_umm,json=distributedUmm,proto3" json:"distributed_umm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailyDistribution) Reset()         { *m = DailyDistribution{} }
func (m *DailyDistribution) String() string { return proto.CompactTextString(m) }
func (*DailyDistribution) ProtoMessage()    {}
func (*DailyDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6e88def4c510ddb, []int{3}
}
func (m *DailyDistribution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailyDistribution.Unmarshal(m, b)
}
func (m *DailyDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailyDistribution.Marshal(b, m, deterministic)
}
func (m *DailyDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailyDistribution.Merge(m, src)
}
func (m *DailyDistribution) XXX_Size() int {
	return xxx_messageInfo_DailyDistribution.Size(m)
}
func (m *DailyDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_DailyDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_DailyDistribution proto.InternalMessageInfo

// GenesisState 固定领取参数与资格公钥。领取资金位于无铸币权限的 claim 模块账户。
type GenesisState struct {
	Authorities           []ClaimAuthority  `protobuf:"bytes,1,rep,name=authorities,proto3" json:"authorities"`
	Denom                 string            `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	FirstClaimUmm         uint64            `protobuf:"varint,3,opt,name=first_claim_umm,json=firstClaimUmm,proto3" json:"first_claim_umm,omitempty"`
	MaxClaimPerAddressUmm uint64            `protobuf:"varint,4,opt,name=max_claim_per_address_umm,json=maxClaimPerAddressUmm,proto3" json:"max_claim_per_address_umm,omitempty"`
	ClaimIntervalSeconds  int64             `protobuf:"varint,5,opt,name=claim_interval_seconds,json=claimIntervalSeconds,proto3" json:"claim_interval_seconds,omitempty"`
	Records               []ClaimRecord     `protobuf:"bytes,6,rep,name=records,proto3" json:"records"`
	UsedCredentials       []UsedCredential  `protobuf:"bytes,7,rep,name=used_credentials,json=usedCredentials,proto3" json:"used_credentials"`
	DailyClaimLimitUmm    uint64            `protobuf:"varint,8,opt,name=daily_claim_limit_umm,json=dailyClaimLimitUmm,proto3" json:"daily_claim_limit_umm,omitempty"`
	DailyDistribution     DailyDistribution `protobuf:"bytes,9,opt,name=daily_distribution,json=dailyDistribution,proto3" json:"daily_distribution"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6e88def4c510ddb, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisState.Unmarshal(m, b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return xxx_messageInfo_GenesisState.Size(m)
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClaimRecord)(nil), "catcoin.claim.v1.ClaimRecord")
	proto.RegisterType((*UsedCredential)(nil), "catcoin.claim.v1.UsedCredential")
	proto.RegisterType((*ClaimAuthority)(nil), "catcoin.claim.v1.ClaimAuthority")
	proto.RegisterType((*DailyDistribution)(nil), "catcoin.claim.v1.DailyDistribution")
	proto.RegisterType((*GenesisState)(nil), "catcoin.claim.v1.GenesisState")
}

func init() { proto.RegisterFile("catcoin/claim/v1/types.proto", fileDescriptor_d6e88def4c510ddb) }

var fileDescriptor_d6e88def4c510ddb = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0x66, 0x69, 0xf9, 0x9b, 0xb6, 0x50, 0x26, 0xa0, 0xab, 0x51, 0xd8, 0x94, 0x44, 0x9b, 0x28,
	0xdd, 0x14, 0x25, 0xd1, 0x0b, 0x2f, 0x10, 0x12, 0x20, 0x78, 0x01, 0x4b, 0x9a, 0x18, 0x6f, 0x36,
	0xd3, 0x99, 0xb1, 0x9d, 0xb0, 0xb3, 0xb3, 0xee, 0xcc, 0x36, 0xdd, 0xc7, 0xf0, 0x21, 0x4c, 0xf4,
	0x4d, 0x78, 0x0a, 0x13, 0x7d, 0x12, 0x33, 0x3f, 0xa5, 0xad, 0x84, 0x9b, 0x66, 0xe7, 0xfb, 0xce,
	0xe9, 0xf9, 0xce, 0x99, 0x6f, 0x0e, 0x78, 0x86, 0x91, 0xc2, 0x82, 0xa5, 0x21, 0x4e, 0x10, 0xe3,
	0xe1, 0xa8, 0x1b, 0xaa, 0x32, 0xa3, 0xb2, 0x93, 0xe5, 0x42, 0x09, 0xd8, 0x74, 0x6c, 0xc7, 0xb0,
	0x9d, 0x51, 0xf7, 0xe9, 0xd6, 0x40, 0x0c, 0x84, 0x21, 0x43, 0xfd, 0x65, 0xe3, 0x5a, 0xdf, 0x3d,
	0x50, 0x3b, 0xd6, 0x21, 0x11, 0xc5, 0x22, 0x27, 0xd0, 0x07, 0x2b, 0x26, 0x83, 0xe6, 0xbe, 0x17,
	0x78, 0xed, 0xb5, 0x68, 0x72, 0x84, 0xbb, 0xa0, 0x66, 0x3f, 0x49, 0x5c, 0x70, 0xee, 0x2f, 0x06,
	0x5e, 0xbb, 0x1a, 0x01, 0x07, 0xf5, 0x38, 0xbf, 0x0b, 0x88, 0xb1, 0x28, 0x52, 0xe5, 0x57, 0x66,
	0x02, 0x8e, 0x35, 0x02, 0x5f, 0x80, 0x8d, 0x04, 0x49, 0x15, 0xdb, 0xa8, 0x22, 0x65, 0x63, 0xbf,
	0x1a, 0x78, 0xed, 0x4a, 0xd4, 0xd0, 0xb0, 0x51, 0xd1, 0x4b, 0xd9, 0xb8, 0xf5, 0x0d, 0xac, 0xf7,
	0x24, 0x25, 0xc7, 0x39, 0x25, 0x34, 0x55, 0x0c, 0x25, 0x70, 0x0f, 0x34, 0xf0, 0xdd, 0x29, 0x66,
	0xc4, 0x69, 0xab, 0x4f, 0xc1, 0xf3, 0x39, 0xe9, 0x8b, 0xf3, 0xd2, 0x03, 0x50, 0x2f, 0x24, 0x25,
	0x31, 0x52, 0xb6, 0x6a, 0xc5, 0x54, 0x05, 0x1a, 0x3b, 0x52, 0xa6, 0xe4, 0x2f, 0x0f, 0xac, 0x1b,
	0x01, 0x47, 0x85, 0x1a, 0x8a, 0x9c, 0xa9, 0x12, 0xb6, 0x40, 0x83, 0x49, 0x59, 0xd0, 0x3c, 0xbe,
	0xa1, 0xe5, 0xb4, 0x66, 0xcd, 0x82, 0x17, 0xb4, 0x3c, 0x27, 0xf0, 0x35, 0x80, 0x94, 0x1c, 0x1c,
	0x1e, 0x76, 0xdf, 0xc7, 0x59, 0xd1, 0x4f, 0x18, 0xd6, 0xb1, 0xa6, 0x7a, 0x3d, 0x6a, 0x3a, 0xe6,
	0xd2, 0x10, 0x17, 0xb4, 0xd4, 0x02, 0x73, 0x3a, 0x12, 0x37, 0x94, 0x18, 0x05, 0xab, 0xd1, 0xe4,
	0x08, 0x5f, 0x81, 0x4d, 0x84, 0x15, 0x1b, 0x21, 0xc5, 0x44, 0x1a, 0x0f, 0x29, 0x1b, 0x0c, 0x95,
	0x9b, 0x4d, 0x73, 0x4a, 0x9c, 0x19, 0xbc, 0xd5, 0x03, 0x9b, 0x27, 0x88, 0x25, 0xe5, 0x09, 0x93,
	0x2a, 0x67, 0xfd, 0x42, 0x53, 0xf0, 0x31, 0x58, 0x29, 0x14, 0x8e, 0x09, 0x2a, 0x8d, 0xce, 0x4a,
	0xb4, 0x5c, 0x28, 0x7c, 0x82, 0x4a, 0xf8, 0x12, 0x6c, 0x90, 0x49, 0xe0, 0xdc, 0xd5, 0xad, 0xcf,
	0xc0, 0x3d, 0xce, 0x5b, 0x3f, 0xaa, 0xa0, 0x7e, 0x4a, 0x53, 0x2a, 0x99, 0xbc, 0x56, 0x48, 0x51,
	0x78, 0x06, 0x6a, 0xc8, 0x4d, 0x83, 0x51, 0xe9, 0x7b, 0x41, 0xa5, 0x5d, 0x3b, 0x08, 0x3a, 0xff,
	0x1b, 0xab, 0x33, 0x3f, 0xb7, 0x8f, 0xd5, 0xdb, 0xdf, 0xbb, 0x0b, 0xd1, 0x6c, 0x2a, 0xdc, 0x02,
	0x4b, 0x84, 0xa6, 0x82, 0xbb, 0x7b, 0xb1, 0x07, 0x6d, 0x87, 0xaf, 0x2c, 0x9f, 0xfa, 0x81, 0x73,
	0xe7, 0x99, 0x86, 0x81, 0xad, 0x1f, 0x38, 0x87, 0xef, 0xc0, 0x13, 0x8e, 0xc6, 0x2e, 0x2a, 0xa3,
	0x79, 0x8c, 0x08, 0xc9, 0xa9, 0x94, 0x26, 0xa3, 0x6a, 0x32, 0xb6, 0x39, 0x1a, 0x9b, 0xf8, 0x4b,
	0x9a, 0x1f, 0x59, 0x56, 0x67, 0xbe, 0x05, 0x8f, 0x6c, 0x16, 0x4b, 0x15, 0xcd, 0x47, 0x28, 0x89,
	0x25, 0xc5, 0x22, 0x25, 0xd2, 0x5f, 0x32, 0x33, 0xda, 0x32, 0xec, 0xb9, 0x23, 0xaf, 0x2d, 0x07,
	0x3f, 0xe8, 0x6b, 0xd2, 0x8f, 0x41, 0xfa, 0xcb, 0xa6, 0xe7, 0xe7, 0x0f, 0xf4, 0x6c, 0x9f, 0x8c,
	0x6b, 0x78, 0x92, 0x03, 0xaf, 0x40, 0xd3, 0x98, 0x6d, 0xea, 0x4d, 0xe9, 0xaf, 0x3c, 0x34, 0xbb,
	0x79, 0x9f, 0xbb, 0xbf, 0xda, 0x28, 0xe6, 0x50, 0x09, 0xbb, 0x60, 0x9b, 0xe8, 0x1b, 0x77, 0x33,
	0x48, 0x18, 0x67, 0xca, 0x74, 0xbf, 0x6a, 0xba, 0x87, 0x86, 0x34, 0x92, 0x3e, 0x69, 0x4a, 0xb7,
	0xfe, 0x19, 0x58, 0x34, 0x26, 0x33, 0x2e, 0xf1, 0xd7, 0x02, 0xaf, 0x5d, 0x3b, 0xd8, 0xbb, 0xaf,
	0xe3, 0x9e, 0xa1, 0x9c, 0x94, 0x4d, 0x72, 0x8f, 0xb8, 0xba, 0xfd, 0xb3, 0xb3, 0xf0, 0xf3, 0xef,
	0x8e, 0xf7, 0xe5, 0x74, 0xc0, 0xd4, 0xb0, 0xe8, 0x77, 0xb0, 0xe0, 0xa1, 0x44, 0x29, 0x16, 0x19,
	0x17, 0x45, 0x5f, 0xd1, 0x90, 0x97, 0xfb, 0x5c, 0xf4, 0x59, 0x42, 0xf7, 0xf1, 0x10, 0xe9, 0x0d,
	0x65, 0x7f, 0x6d, 0xd1, 0x7d, 0x94, 0x65, 0xe1, 0xd8, 0x6d, 0x2d, 0xb3, 0xb2, 0xfa, 0xcb, 0x66,
	0x17, 0xbd, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x61, 0x66, 0x8a, 0xd3, 0x04, 0x00, 0x00,
}

func (this *ClaimRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClaimRecord)
	if !ok {
		that2, ok := that.(ClaimRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Claimer != that1.Claimer {
		return false
	}
	if this.ClaimedUmm != that1.ClaimedUmm {
		return false
	}
	if this.ClaimCount != that1.ClaimCount {
		return false
	}
	if this.LastClaimUnix != that1.LastClaimUnix {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *UsedCredential) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UsedCredential)
	if !ok {
		that2, ok := that.(UsedCredential)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CredentialId != that1.CredentialId {
		return false
	}
	if this.Claimer != that1.Claimer {
		return false
	}
	if this.UsedAtUnix != that1.UsedAtUnix {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ClaimAuthority) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClaimAuthority)
	if !ok {
		that2, ok := that.(ClaimAuthority)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IssuerKeyId != that1.IssuerKeyId {
		return false
	}
	if !bytes.Equal(this.Ed25519PublicKey, that1.Ed25519PublicKey) {
		return false
	}
	if this.Revoked != that1.Revoked {
		return false
	}
	if this.ActivationHeight != that1.ActivationHeight {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DailyDistribution) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DailyDistribution)
	if !ok {
		that2, ok := that.(DailyDistribution)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UtcDay != that1.UtcDay {
		return false
	}
	if this.DistributedUmm != that1.DistributedUmm {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Authorities) != len(that1.Authorities) {
		return false
	}
	for i := range this.Authorities {
		if !this.Authorities[i].Equal(&that1.Authorities[i]) {
			return false
		}
	}
	if this.Denom != that1.Denom {
		return false
	}
	if this.FirstClaimUmm != that1.FirstClaimUmm {
		return false
	}
	if this.MaxClaimPerAddressUmm != that1.MaxClaimPerAddressUmm {
		return false
	}
	if this.ClaimIntervalSeconds != that1.ClaimIntervalSeconds {
		return false
	}
	if len(this.Records) != len(that1.Records) {
		return false
	}
	for i := range this.Records {
		if !this.Records[i].Equal(&that1.Records[i]) {
			return false
		}
	}
	if len(this.UsedCredentials) != len(that1.UsedCredentials) {
		return false
	}
	for i := range this.UsedCredentials {
		if !this.UsedCredentials[i].Equal(&that1.UsedCredentials[i]) {
			return false
		}
	}
	if this.DailyClaimLimitUmm != that1.DailyClaimLimitUmm {
		return false
	}
	if !this.DailyDistribution.Equal(&that1.DailyDistribution) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
